# this is an example of the Codeweather6 API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Weather API
  description: Move your app forward with our Weather Company
  version: "6.0.0"
# the domain of the service
host: localhost:3000
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /city:
    get:
      summary: Weather Forecast
      description: |
        The City path returns the forecast for city requested
      parameters:
        - name: name
          in: query
          description: the name of the City being requested for forecast
          required: true
          type: string
          format: double
      tags:
        - City
      responses:
        200:
          description: An array of forecasts
          schema:
            type: array
            items:
              $ref: '#/city
        default:
          description: Unexpected error
          schema:
            $ref: '#/Error'
